[package]
name = "example-rest-grpc-multiplex"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum" }
futures = "0.3"
hyper = { version = "0.14",  features = ["full"] }
once_cell = "1.12"
prost = "0.10"
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1"}
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.7" }
tower = { version = "0.4", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = { version = "0.7", features = ["prost"] }
